### ISSUE TITLE
Okruh 8 - Konečné automaty

### ISSUE THREAD

**Issue by nicki-krizek** [tomaskrizek/tul-szz-it-nv#11]
[8. - Konečné automaty](https://github.com/tomaskrizek/tul-szz-it-nv/blob/master/08_konecne_automaty/08_konecne_automaty.md)

| Autor | Reviewer | Stav |
| --- | --- | --- |
| @tomaskrizek |  | :eyes: |
### TODO
- [ ] "Porovnání síly konečných automatů" nedal by se nadpis nazvat lépe?
- [x] Uvádět uzávěrové vlastnosti?

**Comment by nicki-krizek** [comment]
Hotovo, může se dělat review.

**Comment by johnymachine** [comment]
neprohlížel jsem to uplne dokladne, ale v jedne ze tech dvou otazke by asi jeste mohla byt definice jazyka

**Comment by johnymachine** [comment]
Jeste by na zacatku mohlo co to je a k cemu to je:

NA wiki je to celkem dobre tak to nejak pokratit 

Konečný automat (KA, též FSM z anglického finite state machine, či DFA z anglického deterministic finite automaton) je teoretický výpočetní model používaný v informatice pro studium formálních jazyků. Popisuje velice jednoduchý počítač, který může být v jednom z několika stavů, mezi kterými přechází na základě symbolů, které čte ze vstupu. Množina stavů je konečná (odtud název), konečný automat nemá žádnou další paměť, kromě informace o aktuálním stavu. Konečný automat je velice jednoduchý výpočetní model, dokáže rozpoznávat pouze regulární jazyky. Konečné automaty se používají při vyhodnocování regulárních výrazů, např. jako součást lexikálního analyzátoru v překladačích. V informatice se rozlišuje kromě základního deterministického či nedeterministického automatu také automat Mealyho a Mooreův.

**Comment by johnymachine** [comment]
Zde také pěkně http://www.matematika.cz/konecny-automat

**Comment by johnymachine** [comment]
co jsou to ty uzávěrové vlastnosti bud bych to tam dal nebo bych to promazl =)

jeste tu je takovy pekny uvod clanek: http://www.matematika.cz/formalni-jazyky

**Comment by nicki-krizek** [comment]
Uzaverove vlasnosti jsem pridal. Shrnuti KA se mi nechce vymyslet, kdyztak tam neco dej :)

**Comment by johnymachine** [comment]
JJ planuji to nějak projet a trochu upravit... =)

**Comment by johnymachine** [comment]
Ty vlastnosti se určitě naučím. =) 

Ps jak to fungovalo, sestavím několik jednodušších KA a pak je spojím skrze Start stav? Tím vznikne NKA a pak ho převedu na DKA?

**Comment by nicki-krizek** [comment]
To spojeni muze byt ruzne. Pokud mas jazyky L1 a L2 a chces aby vysledny automat rozeznaval slova z L1 nebo z L2, potom je spojis pres start stav. Pokud ale chces rozpoznavat takovy slova, ktera zacinaji slovem z L1 a konci slovem z L2, potom je spojis za sebe, tzn koncove stavy prvniho automatu bys privedl do pocatecniho stavu druheho automatu.

**Comment by johnymachine** [comment]
JJ dik, nejak jsem to poopravil a doplnil. Nakonec mi to přišlo vlastne dobre

**Comment by johnymachine** [comment]
trochu jsem přemýšlel nad pravdivostí toho automatu "rozeznává sudý počet nul" najednou si však nejsem jistý a nula mi přijde sudá (i podle dalších zdrojů), pokud je to tak, tak to ten automat neumí ne? =)

edit: už to vidím, jen ten obrázek není úplně přesný
