### ISSUE TITLE
Okruh 30 - Vyhledávání

### ISSUE THREAD

**Issue by johnymachine** [tomaskrizek/tul-szz-it-nv#13]
[30. - Vyhledávání](https://github.com/tomaskrizek/tul-szz-it-nv/blob/master/30_vyhledavani/30_vyhledavani.md)

| Autor | Reviewer | Stav |
| --- | --- | --- |
| @johnymachine |  | :pencil2: |

**Comment by johnymachine** [comment]
Je to takové rozdělané a celkem mi z toho hrabe. Poměrně dost se liší interpretace česká a anglická. (B stromy vs B+ stromy) Navíc jsou ty operace celkem blbě zdokumentované, protože tam dochází k rekurzím, nevím tedy jak to popsat a jestli do toho vůbec zacházet hlouběji.

**Osobně tomu víc asi moc nedám, je potřeba, aby to někdo ještě omrkl. Zmíněnému jsem moc neporozumněl.**

**Comment by johnymachine** [comment]
@mpi77 Koukám, že si bral DB, tam se ty stromy prý používají na indexaci. Možná bys uměl doplnit? =)

**Comment by johnymachine** [comment]
Může někdo chytrý vysvětlit proč je to půlení intervalu log2(n), matematicky mi to vychází. Ale pořád nemůžu přijít na to proč (jak si to rozepsat, dokázat)?

**Comment by tomaskounovsky** [comment]
Zkus se na půlení intervalu dívat jako na obrácený stavění binárního stromu.

Pokud mám jednu vrstvu, tak můžu pomocí jedné operace prohledat 1 prvek.
Pokud přidám druhou vrstvu, tak můžu pomocí dvou operací prohledat 3 prvky.
Třetí vrstva, 3 operace mi prohledaj 7 prvků.
Čtvrtá vrstva, 4 operace prohledaj 15 prvků.
...
k-tá vrstva, k operací prohledá 2^k -1 prvků.

Ergo s lineárním nárůstem počtu operací můžu prohledat exponenciálně tolik prvků.
A obráceně to musí platit taky, pokud mám n = 2^k prvků, tak potřebuju přesně log2(n) = k operací k vyhledání jednoho prvku (když z toho pomocí půlení udělám binární strom, samozřejmě).

**Comment by johnymachine** [comment]
Jo to je ono dík!

**Comment by johnymachine** [comment]
Binární strom je myšleno Binární vyhledávací strom, že jo?

**Comment by nicki-krizek** [comment]
@johnymachine binarni strom = kazdy uzel ma max dva potomky. BVS podle me navic definuje jejich usporadani, aby se v tom pak dalo rychle hledat

**Comment by johnymachine** [comment]
na bin hledani potrebujes mit serazeno takze myslim ze to je prave ono
