### ISSUE TITLE
Okruh 27 - Paralelní systémy

### ISSUE THREAD

**Issue by johnymachine** [tomaskrizek/tul-szz-it-nv#14]
[27. - Paralelní systémy](https://github.com/tomaskrizek/tul-szz-it-nv/blob/master/27_paralelni_systemy/27_paralelni_systemy.md)

| Autor | Reviewer | Stav |
| --- | --- | --- |
| @johnymachine |  | :hourglass: |

**Comment by johnymachine** [comment]
Věci ohledně vláken a procesů pravděpodobně přesunu do operačních systémů #28

**Comment by mpi77** [comment]
dle mého názoru do 13. otázky (#28) patří správa procesů z pohledu OS a otázku 27 bych postavil v duchu DPG (takže vlákna, mpi, ...)

**Comment by johnymachine** [comment]
Mpi bych tam vůbec nedával a jinak myslím, že právě když to přesunu tak to bude odpovídat...

Operační systém a jeho základní úlohy – správa paměti, **správa procesů**, **životní cyklus procesu**, přidělování procesoru, správa periferií, problém uváznutí a metody jeho předcházení.

_Už je právě hotové tam_

Kouknu co by mělo být zde a podle toho bych se rozhodl, jestli tady toho moc nezbude tak to udělám, aby byly otázky délkou vyrovnanější...

**Comment by nicki-krizek** [comment]
Taky bych se primlouval k tomu presunout veci ohledne procesu do OS a tady zminit spis ty veci z DPG. Mozna by nebyl uplne od veci i okrajove to MPI, jako jednu z moznosti tvorby paralelnich aplikaci.

**Comment by johnymachine** [comment]
Vychází mi to tak, že přesně ty dva nadpisy Procesy a Vlákna bych tam šoupnul a zde bych nechal jenom krátkou definici. U těch OS jsem nenašel o tolik víc věcí na vysvětlování, točí se to okolo toho samého... 

Viz zpracované z mapíku

[13 Operační systém a jeho základní úlohy.pdf](https://github.com/tomaskrizek/tul-szz-it-nv/files/284079/13.Operacni.system.a.jeho.zakladni.ulohy.pdf)

**Comment by johnymachine** [comment]
http://home.zcu.cz/~sberanov/

Pro zasmání, na konci porovnání cen

**Comment by johnymachine** [comment]
Rozhodl jsem se, že to tam zopakuji, je to tam z OPS vzaté zase trochu jinak tak si to každý dle libosti přeskočí a je to.

13 => Obsah OPS
27 => Obsah DPG

**Comment by johnymachine** [comment]
Až to bude hotové, tak se můžeme rozhodnout to nějak pokrátit a nalinkovat jedno z druhého.

**Comment by michalmuzicek** [comment]
já osobně zastávám názor, že když se to učíš a uvidíš tu samou věc znova, tak si ji buď připomeneš, nebo ji jednoduše přeskočíš, takže bych to tam klidně nechal

**Comment by mpi77** [comment]
pěkně zpracováno, dle mého názoru to odpovídá na otázku => :eyes:

to MPI mi tam ani nechybí, byť by nebylo na škodu to tam zmínit.
