### ISSUE TITLE
Okruh 14 - Databázové systémy

### ISSUE THREAD

**Issue by mpi77** [tomaskrizek/tul-szz-it-nv#16]
[14. - Databázové systémy](https://github.com/tomaskrizek/tul-szz-it-nv/blob/master/14_databazove_systemy/14_databazove_systemy.md)

| Autor | Reviewer | Stav |
| --- | --- | --- |
| @mpi77 |  | :eyes: |

**Comment by johnymachine** [comment]
Prima, díky že ses zapojil. :+1:

**Comment by mpi77** [comment]
připraveno k review

**Comment by johnymachine** [comment]
doplnil bych tyto dva obrazky, prijdou mi dobre nazorne

https://www.knowbigdata.com/sites/default/files/CAP_0.png
https://lh5.googleusercontent.com/c_vcKz-Jo3XmIHutpOtJxBoysMt_Ny_PL-0cB4Czh4FvIbTEpe9lObaA6sTwsdHJdrtMXqOBNCNoRxYQYnIlu9MxuYIMWcl5dgUSCADFAfOXWuyWRgKWFk99Pg

**Comment by johnymachine** [comment]
Celkově mi to přijde velmi dobré a doporučil bych to do stavu: :eyes:

Jen okolo NoSQL a distibuovaných databází je poměrně stručné, ale možná to na tuto otázku stačí...

K diskuzi:
- Je ObjectRelationMaping = Objektový model? (jaké jsou rozdíly konkrétní případ objektové databáze)?
- Je NoSQL databáze na objektovém modelu?
- Jaké jsou NoSQL databáze a jak jsou rámcově udělány?
- NoSQL, je to vlastně celé jedna velká distribuovaná hashmapa?
- nemá deklarativní dotazovací jazyk => to podle mě není přesné, vždycky když jsem s nějakou dělal tak tam byl SQL like dotazovací engine.

**Možná se ptám hloupě protože o tom nic nevím.** Negooglil jsem, jen mi to po přečtení tohoto není hned jasné... možná opět nadrámec otázky

**Comment by johnymachine** [comment]
Je to v těch otázkách napsaný trochu divně, ten CAP a škálování nespadá jen pod nosql? Možná bych to vyšoupl o úroveň víš... promiň že prudim... =)

**Comment by mpi77** [comment]
Škálování je obecně platné pro jakýkoli systém. V tomto kontextu je to uvedeno v NoSQL, protože tak je otázka položena.

CAP je záležitost pouze NoSQL, takže je to na správném místě.

**Comment by mpi77** [comment]
"Je ObjectRelationMaping = Objektový model?" - NE. ORM se používá jak u OOSŘBD tak i u RMD. Je to technika mapování objektů v databázi na objekty v programu. Nejedná se tedy o integrální součást RMD či OMD.

**Comment by mpi77** [comment]
"Je NoSQL databáze na objektovém modelu" - NE

**Comment by mpi77** [comment]
"Jaké jsou NoSQL databáze a jak jsou rámcově udělány" - konkrétní implementace jsem nepopisoval z toho důvodu, že jich existuje mnoho a dle mého názoru to není náplní otázky

**Comment by mpi77** [comment]
"NoSQL, je to vlastně celé jedna velká distribuovaná hashmapa?" - NE. Existuje více implementací NoSQL, kde každá z nich si data ukládá jinak. Je pravdou, že v hodně případech se jedná o typ klíč:hodnota případně hash, ale nejsou to všechny.

**Comment by mpi77** [comment]
"nemá deklarativní dotazovací jazyk" - JE pravda, protože něco jako SQL u NoSQL nenajdeš. Existují u některých NoSQL i tzv. SQL-like, ale rozhodně to nepokryje plnohodnotné SQL. A taky to souvisí s tím, že by všichni výrobci SQL museli implementovat nějaký společný dotazovací jazyk, což se rozhodně v brzké době nestane. Nyní je to spíš proprietální záležitost.

**Comment by johnymachine** [comment]
Díky za vyčerpávající odpovědi a přesunul bych to na! :eyes:

**Comment by johnymachine** [comment]
Možná by tam mohla být stručná historie, externisty to prý zajímá. =)

Schopnost přidat vlastnosti, aby byly uspokojeny nové nároky uživatelů.

vlastnosti mi přijde takové divné => napsal bych to jako rozšiřování kapacity systému

Jinak => :eyes:

**Comment by johnymachine** [comment]
![image](https://cloud.githubusercontent.com/assets/2737699/15664966/3bd613f0-2708-11e6-9b2b-8279eb50a4e0.png)

**Comment by mpi77** [comment]
k historii jsem nezabíhal úmyslně, protože ta otázka se na ní neptá. samozřejmě ale, že to může být jako námět na vylepšení.

jaké vlastnosti?? to jsem moc nepochopil co jsi tím chtěl vyjádřit.

**Comment by johnymachine** [comment]
u skálování

**Comment by johnymachine** [comment]
ps: historii vynech není na to nikdo v komisích, doťukni tu otázku SQL a jdi od toho :)

**Comment by tomaskounovsky** [comment]
Dotaz: "v relační tabulce nesmí být dva zcela stejné řádky" - nemělo by to být vztažené k primárnímu klíči? Nebo je tohle ještě "o úroveň výš" a integritními omezeními se to nezabývá?

**Comment by mpi77** [comment]
To platí. Vychází to z toho, že kdyby tam byly dva shodné řádky co se primárního klíče (PK) týká, tak by byly porušeny integritní omezení (IO), protože by v db existovaly dva záznamy se stejným PK, což je nežádoucí. A ano, PK je IO.

**Comment by tomaskounovsky** [comment]
To chápu, ptal jsem se protože mi nebylo jasné, jestli se tím myslí celý řádek (i neklíčové atributy) nebo jenom PK. Mohu přeci mít dva řádky s rozdílnými neklíčovými atributy a stejným PK - pak jsem porušil IO, ale ne obecnou podmínku že "v relační tabulce nesmí být dva zcela stejné řádky". Možná je to jenom slovíčkaření, ale někdo v komisi by se toho mohl chytit.

**Comment by mpi77** [comment]
Ano, týká se to PK (IO). Samozřejmě že pro neklíčové atributy se toto nevztahuje.

**Comment by VaclavPalik** [comment]
Zarazi me docela veta:
případná konzistence upřednostněna před ACID

Spis bych tady rekl, ze se dava prednost horizontalnimu skalovani pred ACID. Klasicke relacni databaze totiz velmi spatne horizontalne skaluji, coz je problem pri hromade requestu.

**Comment by VaclavPalik** [comment]
jinak co ORM, jako je hibernate - relacni databaze, OOP na strane aplikace
