### ISSUE TITLE
Okruh 19 - Alternativní přístupy k programování

### ISSUE THREAD

**Issue by johnymachine** [tomaskrizek/tul-szz-it-nv#17]
[19. - Alternativní přístupy k programování](https://github.com/tomaskrizek/tul-szz-it-nv/blob/master/19_alternativni_pristupy_k_programovani/19_alternativni_pristupy_k_programovani.md)

| Autor | Reviewer | Stav |
| --- | --- | --- |
| @johnymachine |  | :hourglass: |
- [ ] rozšířit lambda kalkul
- [ ] opravit nějak rozumně odvozování

**Comment by nicki-krizek** [comment]
**@michalmuzicek ma informace od Malka, ze tuto otazku se nemusime ucit, pokud jsme predmet nemeli. Staci se na zacatku statnic pripomenout.**

**Comment by johnymachine** [comment]
@tomaskrizek heh, mě moc nebaví signály. Nevíš komu se mám připomenout? :)

**Comment by michalmuzicek** [comment]
Jen pro upřesnění, Málek napsal:
seznámil jsem s Vaším problém naši paní sektretářku.
Shodli jsme se na tom, že až budou známé komise, u kterých budete
obhajovat, tak to členům sdělíme a neměli by Vám danou otázku položit.
Pro jistotu to před státnicí u naší paní sektretářky ještě zkontrolujte.

**Comment by johnymachine** [comment]
Já jsem si jako volitelný předmět zase nedal opakování signálů, tak mi to přijde trochu nefér...

**Comment by johnymachine** [comment]
**To je za mne maximum, čeká na opravy...**

**Comment by mpi77** [comment]
drobnosti jsem opravil, nyní :eyes: 

dobrá práce :)
