### ISSUE TITLE
Okruh 4 - Základy klasické kombinatoriky

### ISSUE THREAD

**Issue by nicki-krizek** [tomaskrizek/tul-szz-it-nv#18]
[4. - Základy klasické kombinatoriky](https://github.com/tomaskrizek/tul-szz-it-nv/blob/master/04_zaklady_klasicke_kombinatoriky/04_zaklady_klasicke_kombinatoriky.md)

| Autor | Reviewer | Stav |
| --- | --- | --- |
| @tomaskrizek |  | :eyes: |
### TODO
- [x] Doplnit obrazky k PIE.
- [x] Rozsirit vzorecek na subfaktorialy.

**Comment by nicki-krizek** [comment]
Hotovo, je mozne udelat review. Prosim zkontrolovat vzorecky, mohl jsem nekde udelat chybu.

Mozna by tam byly pekne obrazky pro princip IE nebo rozklad mnoziny, ale zadne jsem nenasel a nechtelo se mi s tim delat.

**Comment by johnymachine** [comment]
Mám k dispozici pět lidí. Kolika způsoby z nich můžu vybrat trojici?

Není tohle spíš kombinace? Mělo by záležet na pořadí ve trojici.

Spíš podle mě takto: Na vsi se každoročně pořádá soutěž v pojídání švestkových knedlíků. Do finálového kola postoupilo celkem sedm umaštěných závodníků. Spočítejte, kolik celkem existuje možností, jak těchto sedm účastníků může obsadit první tři místa.

**Comment by johnymachine** [comment]
Sedí to pak více i s permutací

**Comment by johnymachine** [comment]
ty příklady by to chtělo doladit a přidat i ke kombinacím

možná by tam měla být i multinomická věta a newtonův vzorec

**Comment by johnymachine** [comment]
Tak jsem to vylepšil, doufám že správně...

Zvážil bych jestli tam nemá být multinomická věta a newtonův vzorec.

Plus by mi přišlo dobré tam ofotit příklad toho rozkladu co jsme řešili nejčastěji

**Comment by tomaskounovsky** [comment]
^ Pokud záleží na pořadí, tak je to variace, pokud ne, tak je to kombinace. Zrovna ten příklad s trojicí lidí z pěti bude kombinace, protože trojice Pepa, Franta a Vašek bude stejná i když se Vašek prohodí s Pepou - pořád to sou ti samí lidé.

**Comment by johnymachine** [comment]
Takhle je to tedy dobře ne?

**Comment by tomaskounovsky** [comment]
Já tam teď žádný problém nevidím (alespoň tedy v části definice kombinací, variací a permutací, dál jsem ještě nekoukal)

**Comment by nicki-krizek** [comment]
Ted to vypada ok, mel jsem to predtim asi prohozene.

Jeste tam teda dam ten multinomicky vzorec, newtonuv a rozsirim ty subfaktorialy.

**Comment by johnymachine** [comment]
Jsem na telefonu ale v permutacich s opak. Chybí ve vzorcích nahoře faktoriál

**Comment by nicki-krizek** [comment]
Opraveno, myslim, ze tahle otazke je :eyes:
