### ISSUE TITLE
Okruh 15 - Normalizace, modelování a optimalizace v databázi

### ISSUE THREAD

**Issue by mpi77** [tomaskrizek/tul-szz-it-nv#19]
[15. - Normalizace, modelování a optimalizace v databázi](https://github.com/tomaskrizek/tul-szz-it-nv/blob/master/15_normalizace_modelovani_optimalizace/15_normalizace_modelovani_optimalizace.md)

| Autor | Reviewer | Stav |
| --- | --- | --- |
| @mpi77 |  | :eyes: |

**Comment by mpi77** [comment]
připraveno k review

**Comment by johnymachine** [comment]
Pěkné! 

Super příklady na ty normální formy, tam kde ten příklad není už se ztrácím, to mi bohužel nikdy nebylo úplně jasné...

Pak možná nějaké ukázky/obrázky k těm indexům. (třeba na [wiki ](https://cs.wikipedia.org/wiki/Bitmapov%C3%A9_indexov%C3%A1n%C3%AD)je pěkný příklad k tomu bitmap indexování)

Celkově pěkné a pro potřeby otázky to asi stačí. => :eyes:

**Comment by mpi77** [comment]
Přemýšlel jsem jestli má smysl uvádět příklady i u BCNF a 4-5NF. Ale to už je tak "pokročilé", že na to sotva bude někdy čas. Za nutný základ (i z praxe) považuji 1-3NF, proto jsem zde uvedl příklady.

**Comment by johnymachine** [comment]
Asi jo, ale z popisu si to v podstate taky moc nepredstavim... => nechal bych na dodělat kdyz bude cas

Na druhou stranu v tom [clanku ](http://www.manualy.net/article.php?articleID=13) to je podle me pomerne dobre vysvetleno, tak proc ne (minimalne bych ho tam nalinkoval)

Jeste me napadlo explicitne zminit, ze normalizace zabranuje aktualizacni a podobnym anomaliim (je to myslim nejaky terminus technikus dobry na zmineni ne?)

plus teda podle me ty indexy...

**Comment by johnymachine** [comment]
Drze jsem pridal anomalie a obrázek forem plus odkazy na formy 4. a 5.
Indexy bych asi nerozmazával, to by bylo tak na 15 stran

=> :eyes:

**Comment by johnymachine** [comment]
Plus k ty dekompozici:
![image](https://cloud.githubusercontent.com/assets/2737699/15658169/7e7449a6-26b9-11e6-83d1-dc39312c9371.png)

Tohle je takový teoretický, možná by to chtěli slyšet

Modelování databázového systému můžeme rozložit na několik úrovní:
- konceptuální – analýza logiky systému
- technologickou – datovou
- implementační – fyzickou

**Comment by michalmuzicek** [comment]
přidal jsem
**Aktualizacní anomálie (Codd):**
-  aktualizační anomálie je nechtěný vedlejší efekt operace nad databází, při kterém dojde ke ztrátě nebo nekonzistenci dat

**Comment by tomaskounovsky** [comment]
Nemůžu souhlasit s příkladem na 3NF - entity "Město" (tabulka 9) a "Funkce" (tabulka 10) nejsou ve 3NF. Alespoň to tedy chápu tak že jejich ID je PK a zbytek jsou neklíčové atributy, v tu chvíli je tam ale stejná tranzitivní závislost jako v původní 2NF tabulce (ID -> Město -> PSČ a ID -> Funkce -> Plat).
Osobně bych nechal jako primární klíč PSČ a Funkci a Město a Plat jako neklíčové atributy.

**Comment by michalmuzicek** [comment]
přidal jsem

## Bezztrátová dekompozice

**bezztrátová dekompozice** = proces dělení původní relace na více schémat bez ztráty sémantiky 
- spojení tabulek, které vzniknou dekompozicí musí dát přesně původní tabulku (musí se zachovat závislosti)

**Comment by johnymachine** [comment]
Pokud to není vysloveně několik voleb, nedávej tam prosím odrážky =) dík

**Comment by michalmuzicek** [comment]
ok, síla zvyku :D

**Comment by mpi77** [comment]
Příklad u 3NF jsem opravil. Ano, Město a Funkce jsou pouze ve 2NF. Příklad se ale zaměřuje na ukázání 3NF u entity Zaměstnanec a tam je to názorně vidět.
