### ISSUE TITLE
Okruh 20 : Deterministické časové signály

### ISSUE THREAD

**Issue by michalmuzicek** [tomaskrizek/tul-szz-it-nv#21]
[20. - Deterministické časové signály](https://github.com/tomaskrizek/tul-szz-it-nv/issues/21)

| Autor | Reviewer | Stav |
| --- | --- | --- |
| @michalmuzicek |  | :hourglass: |

**Comment by nicki-krizek** [comment]
- DTFT: Co znamena ta 0 u ![\omega_0](https://latex.codecogs.com/svg.latex?%5Comega_0) ?
- DTFT: Nasobeni signalu v case je konvoluci ve frekvenci: S tim jsem se setkal poprve. Urcite to tak je? Mas nejaky zdroj?
- Nekde bych zvyraznil zakladni rozdil mezi DTFT a DFT - DTFT dava _spojite_ spektrum, zatimco DFT je uz _navzorkovane_ DTFT
- DFT: Nekde poznamenat, ze druha cast DFT (od N/2 dal) je stejna jako ty predchozi hodnoty, akorat s opacnym znamenkem.
- Obecne bych mozna uvedl jednu, dve poznamky o tom, k cemu vlastne D(T)FT je - abych ze signalu (posloupnost hodnot v case) ziskal frekvencni spektrum - jak je ktera frekvence v signalu zastoupena. Ono to tam v podstate je napsane, ale nejak bych to vypichnul, protoze je to podle me zaklad.
- DTFT/DFT: Dovede nekdo vysvetlit, proc je ve vzorecku u toho e minus?
- STFT: uvodni odstavec by mel predstavit ten problem, ze kdyz aplikuju DFT na signal, ktery se hodne meni, tak dostanu data, ktera mi nic nerikaji. Resenim je tedy signal rozkouskovat na casti, kdy se vicemene nemeni, na ty casti aplikovat STFT a ziskat tim spektrogram - informaci, jak se vyviji jednotlive frekvence v signalu v case.
- Okenkovaci fce: asi je to spis osobni preference, ale mozna bych ty poznamky vice strukturoval do nejakych seznamu. Treba u popisu parametru okenkovacich fci jsem se v textu docela ztracel a bylo pro me obtizne uvedomit si, co je vlastne dulezity pojem atd. Mozna by pomohlo i lepe to _zvyraznit_.
- Vzorkovaci teorem: Ve vzorecku bych mozna uvedl > misto vetsi rovno. Pokud se frekvence rovna, muze nastat problem (vzorkovani sinusovky v nulovych bodech).

**Comment by tomaskounovsky** [comment]
- 0 v ![\omega_0](https://latex.codecogs.com/svg.latex?%5Comega_0) značí, že se jedná o jeden (libovolný) konkrétní bod z ![\omega](https://latex.codecogs.com/svg.latex?%5Comega). V textu je to definované: ![\omega \in \mathbb{R}](https://latex.codecogs.com/svg.latex?%5Comega%20%5Cin%20%5Cmathbb%7BR%7D), v bodě ![\omega_0](https://latex.codecogs.com/svg.latex?%5Comega_0) je DTFT korelace signálu ![x[n]](https://latex.codecogs.com/svg.latex?x%5Bn%5D) a komplexní exponenciely ![e^{j n \omega_0}](https://latex.codecogs.com/svg.latex?e%5E%7Bj%20n%20%5Comega_0%7D)
- Násobení signálů v čase = konvoluce ve frekvenci: Musel ses s tím setkat na PZS (přednáška II, slide 19), akorát se to tam jmenuje "Teorém o násobení", což jsem vynechal (přidáno). Jsem si jist že to tak je, ze dvou důvodů:  
  1) je to v přednášce z PZS :D  
  2) kdyby tomu tak nebylo, tak by nedocházelo k roztékání spektra a maskování blízkých frekvencí / slabých komponent  
  Je pravda, že by tam mělo být slovíčko "periodickou", nebo "kruhovou" - opraveno
- DTFT vs DFT: v textu to je, ale dobře, (snad) zvýrazněno
- Oboustranné/jednostranné spektrum: přidáno
- D(T)FT a k čemu je: popravdě nevím kam takovou informaci hodit, protože mi přijde že už tam je a dávat ji tam znovu je redundantní (taky už na tom pár hodin pracuju, takže je to asi jenom můj dojem) - klidně to někde vypíchni
- Mínus v exponentu: Konvence. Pokud otočíš znaménka v exponentu (tak že D(T)FT bude mít kladné a ID(T)FT bude mít záporné), tak se prakticky nic nezmění.
- STFT: problém nastíněn
- Vzorkovací teorém: Definici jsem vzal přímo z přednášek PZS (přednáška IV, slide 20). Pamatuju si, že ohledně krajních bodů se tam vedla nějaká diskuze. V sešitě mám poznámku (u downsamplingu), že je "vhodné zvolit Nyquistovu frekvenci s ostrou nerovností (abychom se vyhnuli aliasingu ve formě stejné frekvence a opačné fáze v krajním bodě)". Nejsem si jist, jestli je ta krajní frekvence takový problém a jestli je ostrá nerovnost úplně nutná, ale rozhodně se tím nic nezkazí - opraveno

**Comment by nicki-krizek** [comment]
Ok, teorem o nasobeni jsem dohledal, mas pravdu. Na prednasce jsem bud spal nebo to byla takova jednorazova informace, se kterou jsem se uz dal nesetkaval, ze jsem ji proste vypustil :)

Za me to je :eyes:
