### ISSUE TITLE
Okruh 21. - LTI číslicové systémy

### ISSUE THREAD

**Issue by michalmuzicek** [tomaskrizek/tul-szz-it-nv#22]
[21. - LTI číslicové systémy](https://github.com/tomaskrizek/tul-szz-it-nv/blob/master/21_linearni_cislicove_systemy/21_linearni_cislicove_systemy.md)

| Autor | Reviewer | Stav |
| --- | --- | --- |
| @michalmuzicek |  | :hourglass: |

**Comment by nicki-krizek** [comment]
LaTeX `.gif` vzorecky jsem nahradil `.svg`

Pokud jsem ti tim zpusobil v lokalnim repu konflikt, tak se omlouvam :)

**Comment by johnymachine** [comment]
kauzualita a stabilita plati pro vsechny systemy je to tak?

a pro LTI navic Linearita a time invariantsnost?

**Comment by michalmuzicek** [comment]
kauzalita a stabilita neplati pro vsechny systemy, ty systemy musi splnit podminku aby byli kauzalni a/nebo stabilni

LTI systemy ovsem musi byt lienarni a invariantni vuci posunu aby byly oznaceny jako LTI

**Comment by nicki-krizek** [comment]
- Impulzni odezva: Napsal bych, ze je odezvda na _jednotkovy impulz_. Slovo Diracuv mam spojene spis s tim analogovym pulzem.
- Casto se zde pouziva pojem _odezva_ jako oznaceni _vystupu_ ze systemu na vstupni signal. Jednoduse se to plete s _impulzni odezvou_. Sjednotil bych terminologii na _vstupni signal_, _vystupni signal_ a _impulzni odezva_.
- Popis LTI systemu: Jeste se da popsat pomoci diferencni rovnice, ne?
- Frekvencni charakteristika: Ziskame ji z DTFT na impulzni odezvu systemu h[n], je to tak? Puvodne tam bylo y[n].
- ROC: TMI, ale to je jedno. Z celyho je podle me podstatny hlavne to, ze DTFT se ziska ze z transformace spravnym dosazenim. Da se rict, ze z-transformace je zobecnenim DTFT? Ma nekdo predstavu, co by se stalo, kdybych dosadil misto jednotkove kruznice neco jineho? Potom by vstup systemu uvazoval komplexni hodnoty misto pouze realnych, je to tak?
- Systemy s linearni fazi: Kdyz si predstavim linearni fazovou char., tak bych rekl, ze se kazda harmonicka slozka zpozdi jinak. Potom by ale doslo k deformaci signalu. Chapu to spatne?

**Comment by michalmuzicek** [comment]
1. opraveno
2. ok, zamenil jsem to za vystup
3. ano určitě, upravil jsem odtabování
4. to se přiznám, že ted nevím jistě.,Pamatuji si jistě, že H(e^j-omega) jsem vždy počítal z diferenční rovnice ve tvaru napr. y[n] = x[n]+2x[n-1]
5. ROC a Z-transformace je pro mě tenkej led, původně jsem si myslel , že to je čistě jen přepsání frekvenční charakteristiky, ale ono to má hlubší dopady, které podle mě pořádně ani nechápu
6. lineární fáze  znamená (pokud vim), že pro všechny frekvence je stejné zpoždění vzorků

**Comment by michalmuzicek** [comment]
přidal jsem tam obrázek ze slidů k frekv. char., základní idea je vskutku aplikace DTFT na h[n], ale já mam ze cvičení zažité dif. rovnice

**Comment by nicki-krizek** [comment]
- frekv. char: Ono je to v dusledku jedno, protoze dif. rovnice a impulzni odezva jsou zamenitelne. Nicmene DTFT aplikovana pouze na vystup y[n] by davala frekvencni charakteristiku nejakeho konkretniho vystupu a ne systemu jako takoveho. Ted je to ok.
- linearni fazi asi radsi nebudem resit :D Proste to budu brat tak, ze linearni se tomu rika tehdy, pokud se vsechny frekvencni slozky zpozdi o stejny pocet vzorku. Mozna bych to tam jeste nejak dopsal nebo zvyrazil.

Jinak bych rekl, ze :eyes:

**Comment by tomaskounovsky** [comment]
ROC: Ano, z-transformace je zobecnění DTFT. Z-transformace počítá korelaci signálu v čase s ![z^{-n ](https://latex.codecogs.com/svg.latex?z%5E%7B-n%7D), kde ![z = r \cdot e^{j\omega}](https://latex.codecogs.com/svg.latex?z%20%3D%20r%20%5Ccdot%20e%5E%7Bj%5Comega%7D), kde _r_ je reálný číslo a odpovídá magnitudě _z_. Z-transformace = DTFT pokud _r = 1_, tedy jednotková kružnice v komplexním prostoru.

**Comment by johnymachine** [comment]
Mám nějaké H(z) jak zjistím ROC a kam se rozpíná? Nějak mi to uniká :)

**Comment by michalmuzicek** [comment]
Přidal sem na konec příklad ze sešitu, jak sme ROC počítali

**Comment by johnymachine** [comment]
stejně to asi moc nechápu :)

**Comment by VaclavPalik** [comment]
No, kdyz mas H(z), tak ho mas dany, rozhodne ROC nemuze zahrnovat zadny pol a pokud je system kauzalni, tak je to vnejsek kruhu. Vono totiz z jednoho H(z) muze vypadnout tech systemu vice, lisicich se pouze v ROC. Takze hledas-li kauzalni system, tak najdes pol, ktery je nejdal od pocatku a ROC prohlasis za vnejsek kruhu s polomerem vzdlenosti tohoto polu.
