### ISSUE TITLE
Okruh 26 - Základní architektury počítačů

### ISSUE THREAD

**Issue by johnymachine** [tomaskrizek/tul-szz-it-nv#23]
[26. - Základní architektury počítačů](https://github.com/tomaskrizek/tul-szz-it-nv/blob/master/26_zakladni_architektury_pocitacu/26_zakladni_architektury_pocitacu.md)

| Autor | Reviewer | Stav |
| --- | --- | --- |
| @johnymachine |  | :pencil2: |

**Comment by johnymachine** [comment]
Základní architektury počítačů, architektury mikroprocesorů, architektury signálových a grafických procesorů, architektury mikrořadičů, hodnocení výkonnosti počítačů, Amdahlův zákon, výkonnostní rovnice procesoru, srovnání systémů CISC a RISC.

@tomaskrizek @michalmuzicek  Poraďte prosím co si podtím představit. Přijde mi, že si pod tím lze představit trochu víc věcí.

Základní architektury počítačů => von Neuman, Harvard
architektury mikroprocesorů => procesorů => CISC, RISC
architektury mikrořadičů => úplně nevím, asi takový ty bločkový schémata?? prototože co výrobce to architektura

**Celkově předpokládám, že je to obsah předmětu ARP - Architektura Počítačů - Kolář**

**Comment by michalmuzicek** [comment]
uf, hardwerarina, tuhle otazku nebudu mit rad.
Co jsem kouknul do slidu kde jsou mikroradice, tak tam zadna zminka o architekturach neni
Jestli nemysli architekturu (jednotne cislo), pak by se dalo rikat ze mikroradice maji RISC arch., omezeny soubor instrukci,nizka cena etc.

**Comment by johnymachine** [comment]
Jsou tam právě architektury mikroprocesorů i architektury mikrořadičů

mikroprocesor => nevím jestli to mám brát jako normální procesor (CISC, RISC) nebo jak?

podle wiki je mikroprocesor  v podstatě nadřazený pojem...

**Comment by michalmuzicek** [comment]
mikroradic je tedy jednoobvodovy mikropocitac
mikroprocesor si myslim ze je proste jen pripad procesoru, kdy jsou pouzity specialni technologie vyroby pro zvetseni integrace
all in all, priznam se ze z toho taky nejsem uplne rozumnej, zakladni rozdil bude asi v tom, co je vsechno zapouzdreno
Mikropocitac bude mit v jednom pouzdre vsechny zakladni jednotky dane architektury, kdezto mikroprocesor bude soucast vetsiho celku, kde budou k nemu pripojene ostatni prvky

**Comment by johnymachine** [comment]
mikropsrocesor == procesor 

asi tedy...

**Comment by johnymachine** [comment]
![http://images.slideplayer.cz/9/2601703/slides/slide_2.jpg](http://images.slideplayer.cz/9/2601703/slides/slide_2.jpg)

**Comment by johnymachine** [comment]
![image](https://cloud.githubusercontent.com/assets/2737699/15547361/bb2e267e-22a3-11e6-83d3-6b70e903b208.png)

dnes uz proste asi mikropsrocesor == procesor

**Comment by michalmuzicek** [comment]
to bych přímo netvrdil, to co mam já v počítači podle mě není mikroprocesor, je to možná slovíčkaření ale přijde mi že mikroprocesor bude mít speciální použití

**Comment by mpi77** [comment]
procesor = CPU = abstraktní pojem pro centrální výpočetní jednotku
mikroprocesor = procesor v jednom fyzickém pouzdře

takže platí: mikropsrocesor != procesor (protože hw != sw)
a také: mikroprocesor = hw implementace procesoru a jiných jednotek nutných pro funkci

**Comment by mpi77** [comment]
[mikrořadič](http://www.root.cz/clanky/mikroradice-a-jejich-pouziti-v-jednoduchych-mikropocitacich/)

a ARP přednáška 2 - Procesory 1.

**Comment by johnymachine** [comment]
Díky za podměty, už jsem to vyřešil a ano je to celkem slovíčkaření

**Procesorem** se rozumí základní jednotka počítače, tj. logický
automat pro zpracování informací, obsahující aritmetickou
jednotku a řadič (počítač bez periferních zařízení a bez
hlavní paměti); chování je definováno programem

**Mikroprocesor** je malý procesor vyráběný technologií velké
integrace, určen především na výpočty a logické funkce;
je přednostně orientován na operace nad slovy.

V podstatě myslím, že je to jak říká Martin, nenapadlo mě to brát podle popisu jako abstraktní pojem a implementaci.

nalezeno v přednáškách z ARP

**Comment by johnymachine** [comment]
Rozlišoval jsem to **micro** jen jako míru integrace.

**Comment by johnymachine** [comment]
Připraveno k review, u těch architektur si nejsem moc jistý jestli to stačí. (kontrolér, signálový a grafický)

Hlavně u toho grafického jsem vařil trochu z vody, k tomu toho moc není k nalezení...

**Comment by michalmuzicek** [comment]
pridal jsem tam jeden bod a obrazek k GPU

**Comment by VaclavPalik** [comment]
(highendova) GPU maji sirsi pametovou sbernici, nez CPU, u CPU je obvykle 128-bit (diky dvoukanalovemu zapojeni), kdezto GPU maji cokoliv od 64-bit (totalni lowend) az nekam po 512-bit. Problemem GPU je hlavne to, ze GPU je mnohem citlivejsi na pametovou propustnost, nez CPU (i bezny integrovany grafiky jsou totiz dosti ciltivy vykonem na to, jestli je zapojenej jenom jeden nebo oba pametove moduly)

**Comment by johnymachine** [comment]
oprav jak myslíš, my o tom nic moc nevíme :)
