### ISSUE TITLE
Okruh 28 - Průmyslové komunikační systémy

### ISSUE THREAD

**Issue by johnymachine** [tomaskrizek/tul-szz-it-nv#24]
[28. - Průmyslové komunikační systémy](https://github.com/tomaskrizek/tul-szz-it-nv/blob/master/28_prumyslove_komunikacni_systemy/28_prumyslove_komunikacni_systemy.md)

| Autor | Reviewer | Stav |
| --- | --- | --- |
| @johnymachine |  | :pencil2: |

**Comment by johnymachine** [comment]
ModBus je určitě protokol ne?

Ale jak je to u ostatních, třeba CAN je podle mě obojí a naopak po některých sběrnicích mohou jít i jiné protokoly?

Kde je zde hranice protokol, sběrnice?

**Comment by nicki-krizek** [comment]
Obecně protokol popisuje způsob komunikace a sběrnice je to, po čem se komunikuje. ModBus je protokol, CAN je asi standard, kterej popisuje jak sbernici tak i protokol komunikace.

**Comment by johnymachine** [comment]
Opravdu nechutná otázka, ke všemu toho jde dát miliarda =)

**Takto to povazuji asi za temere hotove a jdu od toho:**
- [ ] doplnit ethernet (nenasel jsem k tomu nic moc)
- [ ] celkově pokrátit

**Comment by michalmuzicek** [comment]
nedivim se ti, jeste sem se sem nedostal, ale sbernice a spol byly vzdycky peklo, nejdulezitejsi bude podle me abysme meli prehled kde se to pouziva a jak to zhruba pracuje, pripadne cim se lisi (hlavne ty seriove linky)
