### ISSUE TITLE
Schůzka na živo

### ISSUE THREAD

**Issue by johnymachine** [tomaskrizek/tul-szz-it-nv#25]
Navrhuji najít prostory a uspořádat 2x (3x) schůzku na živo. Myslím, že by to bylo fajn si materiály projít společně, prodiskutovat to, navrhnout změny a vzájemně se otázky naučit.

Byl bych pro dva (tři) termíny po týdnu:
- **30. května**
- **6. června**
- 10. nebo 13. května

Jednalo by se více méně o celodenní session i s obědem. Začátek zhruba na 10:00 a do kolika to půjde. Termíny nejsou definitivní, jde spíše o ten týdenní odstup...

Prostory můžeme když tak využít u našich, na TUL, knihovna?

**Comment by michalmuzicek** [comment]
Minimálně jednou bych to udělal a pak uvidíme. Nevím jak si to viděl ty, ale když jsme se tehdy učili v 5 u nás, tak to bylo spíše chaotické a informační hodnota nebyla příliš velká

**Comment by nicki-krizek** [comment]
Prodiskutovat a projit materialy je rozumny, ale vzajemne se to ucit je podle me neunosny. Spis bych to videl tak, ze projedem, co mame, s tim, ze bych klidne hodne veci preskocil. Nejasny veci muzem zkusit projet, ale spis tak ramcove. Je toho podle hrozne moc na to, abychom to byli schopny to za ten den nejak obsahnout.

**Comment by johnymachine** [comment]
@michalmuzicek to je pravda, kdyžtak se mžeme domluvit na nějakých menších skupinkách...

@tomaskrizek no jakoze spis prodiskutovat, v zasade bych si rekl, co by melo ke kazdy otazce smysl rict a aby se to veslo do 6 minut (na ty otazky je asi jen 10 min)

**Comment by nicki-krizek** [comment]
Jak teda zitra? Navrhuju sejit se kolem 10h u kantyny (na poslneni) a projit nejaky ty materialy. Dorazi nekdo?

**Comment by johnymachine** [comment]
Může být, budu tam

**Comment by michalmuzicek** [comment]
ok, my s chibim tam budem taky

**Comment by mpi77** [comment]
já tam zítra určitě nebudu. ale vy to beze mě zvládnete :)

**Comment by michalmuzicek** [comment]
tak co, já osobně bych dal zase sraz v pondělí 6.6.

**Comment by nicki-krizek** [comment]
Dobra, navrhuju se zase sejit kolem 10h pred kantynou a pak vyresime, kam pujdem.

**Comment by nicki-krizek** [comment]
Sorry, dneska nedorazim.

**Comment by michalmuzicek** [comment]
@johnymachine @tomaskrizek 
kdybyste měli zájem tak já s chibim zítra budem od cca 10 hodin ve škole, tak se případně pak můžeme někde sejít
