### ISSUE TITLE
Okruh 13 - Operační systém

### ISSUE THREAD

**Issue by johnymachine** [tomaskrizek/tul-szz-it-nv#28]
[13. - Operační systém](https://github.com/tomaskrizek/tul-szz-it-nv/blob/master/13_operacni_system/13_operacni_system.md)

| Autor | Reviewer | Stav |
| --- | --- | --- |
| @johnymachine |  | :eyes: |

**Comment by johnymachine** [comment]
Je toho nakonec celkem dost a některé věci jsem tedy zopakoval jinak podle přednášek z OPS. Myslím, že to neuškodí a je to tím pádem **připraveno k review**...

**Comment by mpi77** [comment]
k rozhraní os bych přidal informaci o **ABI**

**Comment by johnymachine** [comment]
přidej kam myslíš :)

**Comment by mpi77** [comment]
ve Správě paměti u cache píšeš: "Velikost od 10k do 4G". Měl jsi tím na mysli cache s kapacitou 4 GB?? není to trochu nesmysl? cache na cpu s takovouto kapacitou jsem ještě neviděl...

**Comment by johnymachine** [comment]
ma být spíš mega https://cs.wikipedia.org/wiki/Nehalem (ma chybu ve slajdech) =)

**Comment by mpi77** [comment]
drobnosti jsem opravil, jinak :eyes: 
dobrá práce :)

**Comment by nicki-krizek** [comment]
- Sprava pameti: Doplneno MMU, strankovani, odkladani na disk.
- Sprava procesu: Pridany informace o PCB.
- Zivotni cyklus procesu: Obrazek - urcite muze prejit proces z blokovaneho stavu primo do beziciho? Podleme spis prejde do stavu cekajici, a az potom do stavu bezici.

**Comment by johnymachine** [comment]
Nejsem si jist, ale myslím že jsme to někde řešili. A záleželo na implementaci jestli to jsou jakoby dvě fronty a primárně se odbavuje ta blokovaná nebo se to právě přesouvá do ready.

Ale to trochu matně vzpomínám a možná je to lež

**Comment by johnymachine** [comment]
MMU je SW součást OS je to tak?

Ještě by bylo dobré nějak popsat jak funguje ten swap => když se plní pamět, vezme se nejméně používaná stránka a přesune se na HDD. Pokud proces potřebuje stánku předá se řízení OS (ten najde málo využívané stránky posune je na disk a vrátí to požadovanou) a proces je blokovaný. (To je důležité)

Nějak to tam souvisí s MMU
https://cs.wikipedia.org/wiki/Str%C3%A1nkov%C3%A1n%C3%AD_pam%C4%9Bti

**Comment by johnymachine** [comment]
uz vidim ze MMU je HW

**Comment by johnymachine** [comment]
V tomto kontextu, na co je přidělování paměti dynamicky když jsou tam pak stejně nějaké stranky určité velikosti...

**Comment by nicki-krizek** [comment]
MMU je HW (cast procesoru), cinnost MMU ridi jadro (tedy SW).

Dynamicke pridelovani pameti tak, jak je popsane, je podle me spise takovy teoreticke prezitek, ktery se realne snad nikde nepouzije. Rozdil je asi v tom, ze u dynamickeho pridelovani pameti bys pridelil vzdycky presne tolik, kolik proces chce. A to v jednom souvislem bloku. Kdezto kdyz je to rozdeleny na stranky, tak mu pridelis nekolik stranek, pricemz kazda muze byt uplne jinde a zaroven procesu das nejspis o neco vic pameti, nez chtel (stranka je dale nedelitelna).

**Comment by johnymachine** [comment]
TODO: @tomaskrizek Napsat jak to funguje reálně při swapování stránek s MMU v současných os.

Spodní odstavec..

**Comment by michalmuzicek** [comment]
heleď dotaz, mě přijde že tam máš překlep
Přidělování procesoru
Nepreemtivní (kooperativní) multiprocesing 

nemá tam být multitasking?
multitasking je, pokud vím, to kdy ti běží více procesů (vláken) najednou a ty mezi nima přepínáš v rámci jednoho CPU
multiprocessing je když systém používá 2 a více CPU ke své činnosti

**Comment by johnymachine** [comment]
z podstaty věci multiprocessing (jako více procesů), bylo to takhle někde ve slidech a myslím, že je to dobře

**Comment by nicki-krizek** [comment]
@johnymachine Pridana sprava pameti v soucasnych os.

**Comment by VaclavPalik** [comment]
Transakce, ACID - todle je vec hlavne databazi, presunul bych to do okruhu c. 14
