### ISSUE TITLE
Okruh 17 - Programování síťových operací

### ISSUE THREAD

**Issue by johnymachine** [tomaskrizek/tul-szz-it-nv#30]
[17. - Programování síťových operací](https://github.com/tomaskrizek/tul-szz-it-nv/blob/master/17_programovani_sitovych_operaci/17_programovani_sitovych_operaci.md)

| Autor | Reviewer | Stav |
| --- | --- | --- |
| @johnymachine |  | :eyes: |

**Comment by johnymachine** [comment]
@mpi77 @tomaskrizek 

Nějak mi nedává smysl toto rozdělení socketů (slidy z dpg)
- Unix DomainSockets(POSIX OS)
- NS DomainSockets
- Internet DomainSockets

Unix, jsou nějaká ta speciální systémová implementace meziprocesové komunikace a internet je normální síťový socket, ale co je NS domain?

**Comment by mpi77** [comment]
[unix vs net sockets](http://manpages.ubuntu.com/manpages/precise/man1/socket.1.html)

**Comment by mpi77** [comment]
osobně bych to rozdělil pouze na Unix a Net sockets.

**Comment by johnymachine** [comment]
jj udelal jsem to tak, viz prave pushnuta verze se sockety

**Comment by johnymachine** [comment]
**takto to vidím dostatečné k review**

Nevím jestli ty blokující neblokující jsou přesně, nikde jsem nemohl najít nějakou rozumnou definici tak jsem se to pokusil udělat sám.

_Možná by bylo dobré doplnit zopakování TCP/IP protokolu_

**Comment by michalmuzicek** [comment]
Tady jsem na vážkách, TCP/IP bych spíš zmínil u Ethernetu

**Comment by mpi77** [comment]
já bych tam TCP nedával

**Comment by mpi77** [comment]
dle mého názoru je to ok k té otázce => :eyes:

**Comment by nicki-krizek** [comment]
V casti TCP/IP jsou chyby, jak v textu, tak i v samotnem obrazku. 

Prosim koukni na to jeste jednou a uved tam pouze protokoly, u kterych si ses jisty, ze patri do dane vrstvy. Nekontrolovat jsem vsechno, ale ARP urcite nepatri do sitove vrstvy, ale do linkove (v pripade TCP/IP tedy do network interface). DHCP je napriklad aplikacni protokol (chyba v obrazku). Lepsi skoro obrazek neuvadet, nez nejaky, kde je to spatne napsane.

**Comment by johnymachine** [comment]
@tomaskrizek 

Myslím si, že obrázek je relativně dobře, ARP musí pracovat s IP tudíž je někde na pomezí. Udělal jsem průzkum a zdroje ho řadí na pomezí a nebo níže...

Dole se ty vrstvy asi trochu překrývají a "vrstva síťového rozhraní (network interface)" je trochu divné označení, je to spis fyzická a linková dohromady. Jinak to ovšem podle mne sedí.

**Kolem a kolem, mi to až na ARP přijde ok, ale ani to není vyloženě špatně**

**Comment by nicki-krizek** [comment]
Kdyby byl ARP sitovy protokol, tak by to znamenalo, ze se prenasi pomoci IP. Tzn., ze zdroj a cil by byl identifikovan pomoci IP adresy. ARP ovsem identifikuje zdroj a cil pomoci MAC adresy, protoze IP se snazi zjistit. Datagramy se tedy posilaji v ramci linkove vrstvy a to, jakou nesou zpravu ("Kdo je 192.168.0.1?") je uplne jedno, protoze to jsou data, ktera se posilaji treba od `DE:AD:BE:EF:CA:FE`. ARP je rozhodne na linkove vrstve a ne na sitove, ani na pomezi...

**Comment by nicki-krizek** [comment]
Stejne tak DHCP rozhodne neni na sitove vrstve, ten obrazek je proste spatne a radsi bych ho vyhodil.

Zkus Satrapovi rict, ze ARP nebo DHCP je protokol sitove vrstvy a uvidis tu reakci :D

**Comment by johnymachine** [comment]
![](http://uva.ulb.ac.be/cit_courseware/datacomm/images/tcpiposi.gif)

tu taky
https://technet.microsoft.com/en-us/library/cc958821.aspx

**Comment by nicki-krizek** [comment]
### ARP

ARP je protokol _linkove vrstvy_.

Popis formatu ARP packetu dle [RFC 826](https://tools.ietf.org/html/rfc826) (sekce Packet Format):

```
Ethernet transmission layer (not necessarily accessible to
     the user):
    48.bit: Ethernet address of destination
    48.bit: Ethernet address of sender
    16.bit: Protocol type = ether_type$ADDRESS_RESOLUTION
Ethernet packet data:
    ...
```

V hlavicce packetu jsou jednoznacne Ethernetove adresy - MAC, tedy packet se rozhodne neposila na sitove vrstve.

### DHCP

DHCP je protokol _aplikacni vrtsvy_.

Pouziva architekrutu klient/server, bezi na UDP 67 & 68 a definuje vnitrni strukturu aplikacniho datagramu. Jinak receno, pokud si otevru Wireshark, tak uvidim BOOTP datagram uvnitr UDP datagramu uvnitr IP packetu.

Struktura aplikacniho datagramu (BOOTP) viz [RFC 2131](https://tools.ietf.org/html/rfc2131#page-9).

Jedna se tedy i aplikacni protokol, ktery zajistuje nejakou sluzbu, nikoliv smerovani (ktere zajistuji sitove protokoly).

**Comment by johnymachine** [comment]
Jo to je určitě pravda spíš proč je to všude jinak. Podle mě je nepřesně mapování vrstev iao osi na tcp ip... (dhcp je určitě špatně to jo)

**Comment by johnymachine** [comment]
Kamkoliv jdu, tak nacházím oba názory. Dost se ozývá, že osi iso je model z 90' a tcp ip je proste tak nejak implementováno a uplne neodpovida osi iso (dhcp je aplikacni, protoze komunikuje po UDP a je v user land VS ale zajistuje funkcionality site a je jedno jak je udelan, je to network layer)

Neprijde mi to nijak zasadni a uz se tim nebudu zabyvat, pokud chces uprav to ci smaz. =)

**Comment by michalmuzicek** [comment]
chapu správně, že je debata na téma osi iso vs tcp ip?
co si pamatuju ze střední od kazdy, tak osi iso model a tcp/ip model byly vyvíjené paralelně, tedy jeden nevychází z toho druhého. Ovšem zpětně sepři srovnání řeklo, že první vrstva(ethernet) tcp/ip obsahuje physical a data link vrstvu osi iso, druhá vrstva (network) a třetí (transport) zástavají, a čtvrtá vrstva aplikační odpovídá zbylým třem v osi iso

souhlasím s sharpem, arp je nástroj, který když přijde rámec, který má neznámou cílovou IP adresu (tady si nejsem úplně jistý ale myslím že exituje arp table, kde si uchovává známé IP adresy a korespondující fyzické adresy), tak vyšle fyzický broadcast (ff:ff:ff....) se speciálním dotazem WHOIS spolu s neznámou IP adresou, tento rámec všichni přijmou a jen ten co má tu IP adresu odpoví, čímž z odpovědi si ten daný prvek (většinou router bych řekl) vyextrahuje jeho fyzickou adresu a zašle mu celou zprávu

jedná se tedy o adresaci v rámci LAN, kde se komunikuje pomocí fyzických adres, tedy bych ARP zařadil do linkové vrstvy

**Comment by michalmuzicek** [comment]
nebo alespoň takto si to pamatuji :D

**Comment by johnymachine** [comment]
Jde o to do které vrstvy patří ty protokoly. Zjednodušeně řečeno je DHCP je implementováno vysoko a komunikuje přes UDP, ale v celkovém důsledku musí umět řešit IP komunikaci a zároveň musí obsloužit klienty bez IP pomocí multicastu a mac... a tak někdo bude tvrdit to a někdo tamto

**Comment by michalmuzicek** [comment]
Takle to podle mě probíhá, píšu to spíš že mě zajímá jestli tomu tak je. Chápu že to sou zbytečné detaily, které nebudou potřeba, takže to případně ignoruj :)

DHCP:
Připojíš nový počítač do LANky která má nastavenou výchozí bránu a je to router, na kterém většinou běží DHCP server (může být i dedikovaný).
Nový počítač nemá žádné informace o adresách v LANu (tedy ani neví adresu DHCP serveru), takže v aplikační vrstvě (windowsy) vytvoří DHCP požadavek a ten je poslán do nižších vrstev. V transportní vrstvě je přidelen UDP port 67 , v internetové vrstvě je nastavena broadcast IP adresa a v ethernetové vrstvě fyzický broadcast.
Z principu bych řekl že všechny prvky v síti tenhle packet odchytí, ale všichni krom DHCP serveru ho v transportní vrstvě zahodí, protože nemají otevřený UDP port 67. 
Packet se pak pošle do aplikační vrstvy, kde se zjistí volná IP adresa.
Následně vytvoří odpověď, kterou pošle na fyzickou adresu posílatele. Ten ji přijme a získanou IPnu si nastaví.

**Comment by johnymachine** [comment]
Na začátku není nic, a rozešle se prostě multicast "je tu dhcp?"

https://tools.ietf.org/html/rfc2131#page-9
https://www.cloudshark.org/captures/0009d5398f37

**Comment by nicki-krizek** [comment]
@johnymachine DHCP neresi komunikaci pres IP. Kdyby to tak bylo, museli by byt specifikace pro DHCPv4 a DHCPv6, nicmene DHCP funguje naprosto stejne, at se pro prenos na sitove vrstve pouzije IPv4 nebo IPv6. V dusledku tedy DHCP nic o smerovani paketu a tedy o IP nevi. 

To, ze se s klientem bez IP pouziva broadcast je uplne jedno. DHCP neresi sitovou komunikaci o nic vic nez HTTP nebo SSH. Pro prenos vsech aplikacnich datagramu se samozrejme musi nutne pouzit nizsi sitove vrstvy, ale tem se to proste preda jako data, ktera maji dorucit a vic se to diky abstrakci neresi. HTTP data v dusledku taky behaj po Ethnernetu, ale to neznamena, ze HTTP je fyzickej protokol, ktery by resil casovani bitu

**Comment by johnymachine** [comment]
Souhlasím s největší pravděpodobností to tak je.
