### ISSUE TITLE
Okruh 1 - Základy teorie grafů

### ISSUE THREAD

**Issue by michalmuzicek** [tomaskrizek/tul-szz-it-nv#31]
https://github.com/tomaskrizek/tul-szz-it-nv/blob/master/01_zaklady_teorie_grafu/01_zaklady_teorie_grafu.md

**Comment by johnymachine** [comment]
Způsoby reprezentace grafu

**Comment by johnymachine** [comment]
Není ten zápis spíš takto? V = {1, 2, 3, 4, 5, 6, 7, 8, 9}
H = {(1, 2), (1, 5), (2, 3), (3, 4), (3, 6), (5, 6), (5, 9), (6, 7), (6, 8), (8, 9)}

Myslím že by tě mohl trollovat na závorkách

**Comment by johnymachine** [comment]
i kdyz mozna jen u orientovaneho grafu

**Comment by michalmuzicek** [comment]
jj, pokud vím tak  () označují uspořádanou n-tici, a {} neuspořádanou

**Comment by nicki-krizek** [comment]
- kostra grafu: "minimalni souvisly podgraf..." co tady znamena to slovo minimalni? Nejedna se potom spis o minimalni kostru grafu?
- uplny graf: opravena spatna rovnice pro pocet hran + odvozeni
- obrazek pro boruvkuv algoritmus mi prisel podivnej (udelal z nejakeho podivneho duvodu hodne kroku naraz), ale algoritmus z popisu chapu
- nekde by asi bylo dobre uvest, ze kostra je zaroven i strom

**Comment by michalmuzicek** [comment]
mas pravdu, to jsem prehlidl, tuhle cast sem opisoval ze sesitu (kde to mam napsane kostrbate), ale je pravda ze to nedava smysl, online definice take zni ze kostra grafu je souvisly podgraf, ktery je stromem a obsahuje vsechny vrcholy (tedy faktor grafu)

**Comment by johnymachine** [comment]
Ten kruskal a boruvka mi prijdou dost podobne, nekde se uvadi ze jsou totozne nekde zase ze nejsou...

**Comment by nicki-krizek** [comment]
Kruskal i Boruvka jsou si podobny. Rozdil je v tom, ze Kruskal uvazuje vsechny hrany od nejlevnejsi a Boruvka uvazuje v kazdem kroku pouze hrany, ktere spoji dve ruzne komponenty k sobe.

**Comment by johnymachine** [comment]
acyklický graf - graf, ve kterém neexistuje kružnice, nazýváme les 

Není to spíš strom? =)

**Comment by johnymachine** [comment]
dosti jsem to poladil, prosím o kontrolu

**Comment by michalmuzicek** [comment]
@acyklický graf
to sem opsal ze sesitu, dle online definice to je strom

**Comment by michalmuzicek** [comment]
ted jsem to prohlizel a dostal sem se k definici stromu, doufam ze sem to nebyl ja kdo to tam dal (uz si to nevybavuji) ale Euleruv vzorec pro strom rika ze pocet vrcholu = pocet hran **+** 1 (v materialech bylo napsano -1 )

**Comment by johnymachine** [comment]
To jsem byl já, jo koukám je to prohozené =)

**Comment by VaclavPalik** [comment]
strom musi bejt navic souvisly oproti lesu, takze acyklicky graf (obecne) je les

**Comment by johnymachine** [comment]
ok, tak tam nějak udělej definici obou

**Comment by michalmuzicek** [comment]
ja mel za to, ze les je nesouvisly graf (tedy 2 a vice komponent), ktery je slozen ze stromu

**Comment by johnymachine** [comment]
ano a proto je definice acyklickeho spatne 

acyklický je les a acyklický souvislý je strom => les je několik stromů 

Alespoň podle mě =)

**Comment by VaclavPalik** [comment]
no, acyklicky graf muze bejt souvislej, nebo taky ne.

Jinak si pamatuju, ze zrovna Koucky to rikal takhle, ze acyklicky graf je les a acyklicky souvisly je strom.
Les uvadel pred stromem.
