### ISSUE TITLE
Okruh 11 - Pojmy šifrování

### ISSUE THREAD

**Issue by johnymachine** [tomaskrizek/tul-szz-it-nv#33]
[11. - Pojmy šifrování](https://github.com/tomaskrizek/tul-szz-it-nv/blob/master/11_pojmy_sifrovani/11_pojmy_sifrovani.md)

| Autor | Reviewer | Stav |
| --- | --- | --- |
| @johnymachine |  | :hourglass: |

**Comment by johnymachine** [comment]
Má někdo ponětí co je to NDS šifra? 

Edit: NDS (New data seal)

**Comment by michalmuzicek** [comment]
no, koukam ze ji ani nejsem schopen najit ve slidech KASu

**Comment by johnymachine** [comment]
udělal jsem co jsem mohl, k u DES, AES a NDS je to slabý... krom AES jsem nenašel moc jednoduchých a rozumných informací (NSA to schovává z google search) a ani to nejsou moc věci co člověk vysvětlí z hlavy...

**Mrkněte na to => review**

**Comment by nicki-krizek** [comment]
- pridana pozn u hillovy sifry, ze cisla jsou mod (delka abecedy), nejdriv jsem na to koukal a nedochazelo mi to :)
- viegnerova sifra, opraven vzorecek, predpokladam, ze to ma byt Ti + Ki a jen chybelo plus
- pridan rozcestnik k symetrickym sifram
- pridany vzorecky pro sifrovani, desifrovani RSA + priklad s mensimi exponenty

**Comment by nicki-krizek** [comment]
AES, DES pro me bylo skoro TL;DR, stejne neni mozny si pamatovat, co se tam vsechno deje, kdy a jak. Dulezity je podle me pochopit, ze se tam pouziva ten princip Feistelovy sifry.
NDS jsem taky neznal a ani ted tomu moc nerozumim... Asi bych to ale nejak vic nerozvadel.

-> :eyes:
