### ISSUE TITLE
Okruh 25 - Zásady návrhu elektronických systémů

### ISSUE THREAD

**Issue by johnymachine** [tomaskrizek/tul-szz-it-nv#34]
[25. - Zásady návrhu elektronických systémů](https://github.com/tomaskrizek/tul-szz-it-nv/blob/master/25_zasady_navrhu_elektronickych_systemu/25_zasady_navrhu_elektronickych_systemu.md)

| Autor | Reviewer | Stav |
| --- | --- | --- |
| @johnymachine |  | :hourglass: |

**Comment by johnymachine** [comment]
**Připraveno na review** nevím jestli jsem všemu plně porozuměl, tak snad...

**Comment by nicki-krizek** [comment]
Navrh ridici casti: kdyz uz zminujes Moore/Mealy, bylo by dobre tam uvest dve poznamky, ktery dela co a jaky je v nich rozdil. (Jeden reaguje na vstup + pamet, druhy meni stav pouze na zaklade vnitrniho stavu a ten je od toho druheho zpozden o 1? takt)

**Comment by johnymachine** [comment]
doplneno, ale jen ve strucnosti s odkazem ven
