### ISSUE TITLE
Okruh 3 - Rekurentní vztahy

### ISSUE THREAD

**Issue by tomaskounovsky** [tomaskrizek/tul-szz-it-nv#35]
https://github.com/tomaskrizek/tul-szz-it-nv/tree/master/03_rekurentni_vztahy

**Comment by johnymachine** [comment]
@tomaskounovsky 

Byl bych proto, změnit tam ten příklad za nějaký úplně triviální. Nerad bych se tam naostro zasekl s tema odmocninama... =)

**Comment by johnymachine** [comment]
I když asi stačí ty příklady pod...

**Comment by johnymachine** [comment]
PS: cenda tam mel nejaky chyby v tom prvnim, to druhe nevim to jsem nepocital

**Comment by tomaskounovsky** [comment]
Hele zrovna Fibonacci je asi to nejtriviálnější co můžeš dostat a nedivil bych se kdyby zrovna na tom si měl předvést výpočet, vzhledem k tomu že to je jeden z nejznáměnšjčích rek. vztahů. Mám to tam rozepsaný krok po kroku, tak snad to zas takový peklo není :)

Čendův příklad z pdf jsem prohnal wolframem, výsledky má správně. Jestli se někde upsal v postupu nevím, zas tak moc jsem to nezkoumal.

**Comment by johnymachine** [comment]
V tom fib je chyba koreny jsou podle me (1+sqrt(5))2 a (1-sqrt(5))2

**Comment by tomaskounovsky** [comment]
Jo, to máš pravdu - opraveno.

**Comment by nicki-krizek** [comment]
Opravil jsem par chyb a pojmu. Zkontroloval jsem pouziti vytvorujicich fci. Prednasku ohledne soustavy rek. vztahu jsem nenasel.

Akorat si nejsem jisty:
- ve 3 u [char. polynom > srozumitelne](https://github.com/tomaskrizek/tul-szz-it-nv/blob/master/03_rekurentni_vztahy/03_rekurentni_vztahy.md#srozumiteln%C4%9B): Nechybi ve vysledku imaginarni jednotka u sin?

**Comment by nicki-krizek** [comment]
Primo ve zneni otazky je - otazka existence a jednoznacnosti reseni. Jak to je?

Reseni je pro kazdy rekurentni vztah nekonecne mnoho (vsechny cleny vsech posloupnosti, ktere mu vyhovuji). Pokud mam pocatecni podminky, tak jich je taky nekonecne mnoho (vsechny cleny te dane posloupnosti, ktera je udana pomoci pocatecnich podminek). 

U homogennich vztahu je dale napsano, ze existuje k lin. nezavislych reseni (tzn. ruznych posloupnosti?). Da se nejak urcit, kolik techto reseni je?

**Comment by tomaskounovsky** [comment]
imag u sin: Jo, asi mi uteklo. opraveno.

Existence a jednoznačnost řešení: Je to uvedeno v ![Platí](https://github.com/tomaskrizek/tul-szz-it-nv/blob/master/03_rekurentni_vztahy/03_rekurentni_vztahy.md#plat%C3%AD) u homogenních vztahů. Řekl bych že za "jednoznačné řešení" se zde považuje "jedna posloupnost". Samozřejmě to je nekonečně prvků, ale jsou jednoznačně dány a tvoří jedinné možné řešení, ať už si pak za _n_ dosadíš cokoliv.

U těch homogenních vztahů, ano, viděl bych to tak. _k_ lineárně nezávislých řešení znamená _k_ lin. nez. posloupností, které odpovídají rekurentnímu vztahu čádu _k_. Nechápu druhou otázku, prostě jich bude _k_ a jakoukoliv jejich lineární kombinací získáš libovolné jiné řešení, kterých je nekonečně mnoho.

**Comment by nicki-krizek** [comment]
Jo, uz to chapu.

k je vlastne rad toho rekurentniho vztahu.
