### ISSUE TITLE
Okruh 5 - Vytvořující funkce

### ISSUE THREAD

**Issue by michalmuzicek** [tomaskrizek/tul-szz-it-nv#36]
https://github.com/tomaskrizek/tul-szz-it-nv/blob/master/05_vytvorujici_funkce/05_vytvorujici_funkce.md

**Comment by johnymachine** [comment]
Myslím že by tu měly být odpovědi na kocourovskou otázku "Co to je??"
- Vytvořující funkce => pokud se nepletu tak jedno z možných vyjádření posloupnosti
  - proč to takhle dělat je to v něčem lepší?
- Věžové polynomy
  - Co to je?
  - "Na co to je dobrý krom šachů?" =)

**Comment by michalmuzicek** [comment]
- doplněno (do jisté míry), nevim jestli plně chápu jejich praktické využití
- doplnil jsem definici, opět reálné použití moc nedávám

**Comment by johnymachine** [comment]
Bylo by dobré asi mít u té tabulky i příslušný otevřený tvar... (pracné)

Pak by tam asi měla být ta sranda že N ty člen je nta derivace lomeno n faktorial

A u těch věžáků se to dá vysvětlit na tom, že máme 4 osoby a každá má nějaké preference (měl to někde jako programátoři a jazyky které kdo umí)

**Comment by michalmuzicek** [comment]
- popravdě když máš výpis prvků posloupnosti, tak vytvořit otevřený tvar je vcelku jednoduché (dokud v té posloupnosti vidíš pattern)
- přidáno
- přidáno

**Comment by nicki-krizek** [comment]
K vezovym polynomum by toho mohlo byt u neco vic, chybi mi tu napr.:
- invariantnost vuci posunu (lze libovolne prohazovat radky a sloupce)
- popis pripadu vypoctu, kdy uvazuju, ze bud umistim vez a nebo ji neumistim, ktery pak scenar rozlozi na dva jednodussi pripady r(x,C) = x*r(x,C1) + r(x, C2)
- u prikladu s inverznimi polynomy nerozumim tomu, kde se tam berou ty kombinace, navic mi to prijde zbytecne, kdyt je to vzdycky 1

**Comment by tomaskounovsky** [comment]
@tomaskrizek Pozor u těch inverzních rook polynomů, kombinace 5 z 5 (4 ze 4, 3 ze 3 atd) sice vždycky vyjde 1, ale tahle kombinace tam bude _pouze_ při výpočtu x^5, tedy rozdávám 5 věží. Pokud chceš vypočítat třeba x^3 (rozdávám tři věže), tak to bude kombinace 3 z 5 (a pak 2 ze 4 a nakonec 1 ze 3).

**Comment by nicki-krizek** [comment]
Aha... Mozna by bylo dobre tam treba ten obecny vzorecek + napsat a poznamenat, co predstavuje to C, A (resp. ty cisla u toho).

**Comment by tomaskounovsky** [comment]
Jo, to asi jo. Koucký na přednášce ukazoval příklad podobný,

**Comment by tomaskounovsky** [comment]
/sigh... sorry, to tlačítko "close and comment" by mi měli zakázat.

**Comment by michalmuzicek** [comment]
- přidal jsem tam invariantnost
- přidán příklad rozkladu
- zde moc nepomůžu, já si to pamatuju jako dogma

**Comment by johnymachine** [comment]
@michalmuzicek 

prijde mi ze ten rozklad je spatne

**Comment by michalmuzicek** [comment]
mas pravdu je
oprava, vysledek je podle me spravne, ale v te graficke reprezemtaci C1 nema byt kriz, ale jen polozeny T, nicmene polynomove vyjadreni je spravne

**Comment by johnymachine** [comment]
@michalmuzicek ještě prosím jestli bych ve volném čase (okrajově není to nutné) mohl trochu poopravit své otázky. (Možná i TK @tomaskounovsky)) Když jsem generoval se striktnějším parserem tak nastaly chybky:
- Nemáte před křížky u nadpisu mezeru a pak se to generuje špatně.
- Některé obrázky vedou ven na nějaké posting a při renderovaní to házelo chyby (nejlépe všechny obrázky lokálně a linkovat relativně).
- Obrázek prosím linkovat z mezerou před mezerou popiskem a mezerou. (v některých případech to máš jako součást listu a dělá to bordel).

Chápu však, pokud se vám do toho už nechce, protože github si s tím i tak poradí... =)

**Comment by michalmuzicek** [comment]
Hele, po statnicich se na to klidne vrhnu
