### ISSUE TITLE
Okruh 7 - Časová náročnost algoritmů

### ISSUE THREAD

**Issue by nicki-krizek** [tomaskrizek/tul-szz-it-nv#37]
[7. - Časová náročnost algoritmů](https://github.com/tomaskrizek/tul-szz-it-nv/blob/master/07_casova_narocnost_algoritmu/07_casova_narocnost_algoritmu.md)

| Autor | Reviewer | Stav |
| --- | --- | --- |
| @tomaskrizek |  | :eyes: |

**Comment by johnymachine** [comment]
https://www.youtube.com/watch?v=YX40hbAHx3s

**Comment by nicki-krizek** [comment]
Otázka je možná trochu stručná, ale snad odpovídá na všechno. V sešitě z KME jsem k této problematice ještě našel kapitolu ohledně určování složitosti rekurzivních algoritmů divide and conquer. Nicméně to mi přišlo dost složité a asi to úplně není součástí otázky, tak to vynechávám.

**Comment by johnymachine** [comment]
Neudává se i v nejlepším případě?

A pak by tam mělo být Amortizovaná vs. asymptotická složitost

**Comment by tomaskounovsky** [comment]
Best case se uvádět může, ale nemá to moc význam. Třeba vyhledávací algoritmy můžou snad vždy mít složitost v nejlepším případě 1 (prostě se hned trefíš na hledanej prvek), ale to ti je ve výsledku k ničemu, když to nemůžeš zaručit.

**Comment by nicki-krizek** [comment]
Best case se obcas taky uvadi, ale prislo mi to zbytecny zminovat.

Jakej je rozdil mezi amortizovanou vs asymptotickou nevim, tak to kdyztak prosim dopln.

**Comment by johnymachine** [comment]
To jsem právě úplně nepochopil jen vím že se s těmi termíny nějak operuje v této souvislosti

https://www.algoritmy.net/article/3024/Amortizovana-slozitost

**Comment by nicki-krizek** [comment]
Doplneno jak jsem pochopil amortizovanou slozitost. Mozna by se to dalo vysvetlit i lepe, ale podstatu jsem snad zachytil. Povazuju to za :eyes:
