### ISSUE TITLE
Okruh 10 - Turingův stroj

### ISSUE THREAD

**Issue by nicki-krizek** [tomaskrizek/tul-szz-it-nv#38]
[10. - Turingův stroj](https://github.com/tomaskrizek/tul-szz-it-nv/blob/master/10_turinguv_stroj/10_turinguv_stroj.md)

| Autor | Reviewer | Stav |
| --- | --- | --- |
| @tomaskrizek |  | :eyes: |

Takovy popularni tema a nikdo ho nechtel? Ja se toho teda ujmu :)
### TODO
- [x] Je halting problem parcialne rozhodnutelny? Casto se da najit, ze je nerozhodnutelny, ale vypada to, ze je to mysleno ve smyslu, ze neni totalne rozhodnutelny. Prosim o overeni. (@vaclavpalik by urcite vedel.)

**Comment by michalmuzicek** [comment]
původně jsem plánoval, že na to zítra po konferenci skočím, ale vůbec mi nevadí, že si mě předběhl :D

**Comment by nicki-krizek** [comment]
Hotovo, pripraveno k review. Nejsem si jisty, jestli je Halting problem nerozhodnutelny nebo parcialne rozhodnutelny.

@johnymachine Muzes zkusit napsat e-mail Vencovi Palikovi, jestli by na to kouknul? Ten podle me bude vedet. Kdyztak se ho zeptej, jestli by nekouknul i na ty ostatni automaty a gramatiky. Diky.

**Comment by michalmuzicek** [comment]
@tomaskrizek z meho sesitu : problem zastaveni pro TS je nerozhodnutelny (tedy neni TR)
tzn. ze neexistuje algoritmus, ktery by pro dany TS M nad sigma a dane slovo w ze sigma\* zjistil zda stroj M zastavi po predpolzeni slova w

**Comment by michalmuzicek** [comment]
wtf a dale : problem zastaveni pro TS je parcialne rozho. ale neni totalne -> Univerzalni TS

**Comment by johnymachine** [comment]
[TAS-prednasky_zada_all.pdf](https://github.com/tomaskrizek/tul-szz-it-nv/files/297664/TAS-prednasky_zada_all.pdf)

**Comment by nicki-krizek** [comment]
Problem zastaveni podle me bude parcialne rozhodnutelny, protoze muzu sestavit TS, ktery bude simulovat cinnost daneho stroje. Ten potom:
- zastavi akceptovanim, pokud puvodni stroj zastavi
- v opacnem pripade bud zastavi zamitnutim nebo cykluje.

Podstatne je, ze muze i cyklovat, proto nikdy nemuze byt totalne rozhodnutelny.

**Comment by VaclavPalik** [comment]
No, co jsem pogoogloval, tak jako nerozhodnutelny problemy se oznacujou ty, ktery nejsou totalne rozhodnutelny (tzn. muzou bejt parcialne rozhodnutelny, ale taky ne). Taky bezne uvadenej dukaz tvrdi, ze problem nelze rozhodnout totalne. O parcialni rozhodnutelnosti jsem ale zatim nic nenasel, zkusim se na to jeste podivat.

**Comment by VaclavPalik** [comment]
btw zejtra projedu vsechny otazky na automaty a kdyztak k nim doplnim, pripadne upresnim nektery veci

**Comment by johnymachine** [comment]
Možná doplnit něco o ekvivalenci TS T1=T2 a kdy T1<T2

**Comment by johnymachine** [comment]
Plus definovat co znamená akceptuje a co znamená zamítne:

Slovo w je TS akceptováno, dosáhne-li stroj stavu STOP (koncového) a výpočet pak končí.
Slovo w je TS zamítnuto, jestliže:

1. hlava je nad nejlevějším polem a je dán příkaz pohybu vlevo,
2. dosáhne-li výpočet jistého stavu i, z něhož vycházejí hrany viz obr., ale přitom symbol pozorovaný hlavou stroje je různý od a1, a2, a3, . . . an  (stroj „nemůže dál“).

**Comment by johnymachine** [comment]
problém zastavení TS je parciálně rozhodnutelný.

**Comment by johnymachine** [comment]
Přeházel jsem to a poupravil pro lepší čitelnost. Doufám, že to neva...

**Zbývá tedy nastíněný problém: Je halting problem parcialne rozhodnutelny?**

**Comment by VaclavPalik** [comment]
podle https://books.google.cz/books?id=kmaBCwAAQBAJ&pg=PA874&lpg=PA874&dq=halting+problem+partially+decidable&source=bl&ots=8Y5iC5HGfq&sig=mAut-6wTNZ-Cd32YVJZmvSb_V9Y&hl=cs&sa=X&ved=0ahUKEwju0YSIjJHNAhXKPRQKHXHrBXY4ChDoAQgaMAA#v=onepage&q=halting%20problem%20partially%20decidable&f=false

je parcialne rozhodnutelny

**Comment by VaclavPalik** [comment]
Tedka me napada duvod (a vicemene dukaz, ze to tak je): proste ten TS orig upravis tak, aby nemohl rict NE (misto toho ten TS rekne ANO) a spustis ten puvodni algoritmus, pokud zastavi, tak zastavi odpovedi ANO, cykloval-li puvodni TS, tak cykluje i tento, to na parcialni rozhodnutelnost staci
