### ISSUE TITLE
Okruh 18 - WWW aplikace

### ISSUE THREAD

**Issue by nicki-krizek** [tomaskrizek/tul-szz-it-nv#9]
[18. - WWW aplikace](https://github.com/tomaskrizek/tul-szz-it-nv/blob/master/18_www_aplikace/18_www_aplikace.md)

| Autor | Reviewer | Stav |
| --- | --- | --- |
| @tomaskrizek |  | :eyes: |

**Comment by nicki-krizek** [comment]
Doděláno, čekám na review.

**Comment by mpi77** [comment]
k PHP bych doplnil do výčtu: skriptovací jazyk (když to je napsané u Pythonu, tak u PHP by si to také zasloužilo)

**Comment by mpi77** [comment]
jinak ok -> :eyes:

**Comment by johnymachine** [comment]
Možná bych rozšířil REST a WS

jinak => :eyes:

**Comment by johnymachine** [comment]
ještě k uchování stavové informace co takové ty html5 storage...

**Comment by johnymachine** [comment]
možná pak jenom zmínka, že s bouřlivým vývojem se dostávají do prohlížečů různá geo a sensor api a blíží se to nativní aplikaci

**Comment by mpi77** [comment]
já bych zase ws dále nerozšiřoval, protože ta otázka se na ně vůbec neptá. současný rozsah bych považoval za dostačující - je zmíněno že to existuje spolu s několika základními informacemi.

**Comment by mpi77** [comment]
html5 storage není přímo určeno k uchování stavové informace. od toho jsou cookies a sessions. storage (local nebo session) jsou záležitostí pouze na klientovi a webový server s nimi nemá co dělat a nedokáže tak identifikovat klienta podle něj. storage je spíš "cache" pro data, aby se klient nemusel pořád obracet na server. samotnou identifikaci stavu tak vůbec neřeší.

**Comment by mpi77** [comment]
max bych html5 storage zařadil do "Client side/Javascript" jako zmínku, že to existuje

**Comment by nicki-krizek** [comment]
Doplněno:
- PHP skriptovaci jazyk,
- odkaz na local storage (HTML - podpora offline aplikaci)

Takovy drobnosti tam rovnou doplnujte :)
